steps:
  - label: "Bazel"
    commands:
      - echo "+++ Build"
      - bazel build :swiftlint
      - echo "+++ Test"
      - bazel test --test_output=errors //Tests/...
  - label: "Danger"
    commands:
      - echo "--- Bundle Install"
      - bundle install
      - echo "+++ Run Danger"
      - bundle exec danger --verbose
  - label: "Analyze"
    commands:
      - echo "+++ Build"
      - bazel build swiftlint
      - echo "+++ Analyze"
      - bazel test --spawn_strategy=local --test_env=PROJECT_ROOT=$(bazel info workspace) analyze
